apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-06-18T15:13:38Z"
  labels:
    app: gomandel
    app.kubernetes.io/component: gomandel
    app.kubernetes.io/instance: gomandel
    app.kubernetes.io/name: gomandel
    app.kubernetes.io/part-of: gomandel-app
  name: gomandel
  namespace: stress
  resourceVersion: "67952"
  uid: e446a8e8-da80-44c8-b24c-6de450648805
spec:
  clusterIP: 10.217.5.214
  clusterIPs:
  - 10.217.5.214
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gomandel
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
