kind: Deployment
apiVersion: apps/v1
metadata:
  annotations: {}
  name: stress-ng

  namespace: stress
  labels:
    app: stress-ng
    app.kubernetes.io/component: stress-ng
    app.kubernetes.io/instance: stress-ng
    app.kubernetes.io/name: stress-ng
    app.kubernetes.io/part-of: stress-ng-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-ng
  template:
    metadata:
      labels:
        app: stress-ng
        deployment: stress-ng
    spec:
      containers:
        - name: stress-ng
          image: quay.io/brochwer/stress-ng:latest
          # command: ["stress-ng"] 
          # args: ["--brk", "2", "--stack", "2", "--bigheap", "2"]
          resources:
            limits:
              memory: 3Gi
            requests:
              cpu: 1000m
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop: 
              - ALL
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
